# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  app.mail_from_name: "Usygec"
  app.mail_from_address: "postmaster@usygec.fr"
  csv_directory: "%kernel.project_dir%/public/uploads/csv"
  app.mailjet_key_public: "%env(MAILJET_PUBLIC_KEY)%"
  app.mailjet_key_private: "%env(MAILJET_PRIVATE_KEY)%"
  app.dkim_key_path: "%env(DKIM_KEY_PATH)%"

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # Twig\Extra\Intl\IntlExtension:
  #   tags: [twig.extension]

  App\EventSubscriber\SessionEventSubscriber:
    tags:
      - { name: kernel.event_listener, event: security.interactive_login }

  App\EventSubscriber\LogoutEventSubscriber:
    tags:
      - { name: kernel.event_listener, event: security.logout }

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name

  App\:
    resource: "../src/*"
    exclude: "../src/{DependencyInjection,Entity,Tests,Kernel.php}"

  App\Entity\:
    resource: "../src/Entity"
    public: true
    tags: ["doctrine.orm.entity_listener"]

  App\Controller\:
    resource: "../src/Controller"
    tags: ["controller.service_arguments"]

  App\Service\MailJetService:
    arguments:
      $mailjet_key_public: "%env(MAILJET_PUBLIC_KEY)%"
      $mailjet_key_private: "%env(MAILJET_PRIVATE_KEY)%"

  App\Service\SendMailService:
    arguments:
      $dkim_key_path: "%app.dkim_key_path%"
      $project_dir: "%kernel.project_dir%"

  App\Service\CompanyCsvManager:
    arguments:
      $companyRepository: '@App\Repository\RepositoryBam\CompanyRepository'

  Knp\Component\Pager\PaginatorInterface: "@knp_paginator"
