nucleos_dompdf:
  defaults:
    DOMPDF_ENABLE_PHP: true
    chroot: "%kernel.project_dir%/public/images" # See https://github.com/dompdf/dompdf/wiki/Usage#security-restrictions-for-local-files
    logOutputFile: "" # Prevent creating `/tmp/log.htm` which causes problems in some server configurations
