vich_uploader:
  db_driver: orm

  mappings:
    company_image_banner:
      uri_prefix: /images/companies
      upload_destination: "%kernel.project_dir%/public/images/companies"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove:

    user_csv_files:
      uri_prefix: /public/uploads/csv
      upload_destination: "%kernel.project_dir%/public/uploads/csv"
